fixed bugs in tutorial reST source.
git-svn-id: https://mdp-toolkit.svn.sourceforge.net/svnroot/mdp-toolkit/mdp/trunk@672 c860887f-54fc-0310-8c92-9a9c51041e24

diff --git a/tutorial_src/genhtml b/tutorial_src/genhtml
--- a/tutorial_src/genhtml
+++ b/tutorial_src/genhtml
@@ -22,6 +22,10 @@ python modify_header.py > $TEMP
 TUTHTML=tutorial.html
 RST="rst2html -g -t --stylesheet=styles.css" 
 $RST $TEMP $TEMPD
+if [ $? -ne 0 ];then
+    echo "Error compiling tutorial!"
+    exit -1
+fi
 # enclose body of $TEMP with our headers and footers
 # and copy it into the right place
 python remove_header.py $TEMPD $TUTHTML
